export const site = {
    navLinks: [
      { label: "Home", href: "/" },
      { label: "Services", href: "/services" },
      { label: "About", href: "/about" },
      { label: "Process", href: "/process" },
      { label: "Contact", href: "/contact" },
    ],
    hero: {
      badge: "Trusted by law firms nationwide",
      headline: "Remote legal and operations staffing you can trust",
      subheadline: "We place vetted remote legal and operations talent that plugs into your workflow quickly.",
      trustPoints: [
        "Rigorous vetting and legal industry experience",
        "Bilingual talent aligned with U.S. workflows",
        "Scalable from one hire to full remote teams",
      ],
      cta: {
        requestQuote: { label: "Request a Quote", href: "/request-quote" },
        bookCall: { label: "Book a Call", href: "#" },
        whatsapp: { label: "WhatsApp", href: "#" },
      },
    },
    sections: {
      services: "Our Services",
      differentiators: "Why Choose Us",
      differentiatorsSubhead: "Built different. Built to deliver.",
      servicesLabel: "What we do",
      processLabel: "How it works",
      foundersLabel: "The team",
      process: "Our Process",
      founders: "Our Founders",
      finalCta: "Ready to Get Started?",
      finalCtaSubtext: "Connect with us to discuss your staffing needs. We\u2019re here to help you scale with the right talent.",
    },
    trustedBy: {
      label: "Trusted by forward-thinking law firms and service companies",
      logos: [
        "Personal Injury Firms",
        "Immigration Practices",
        "Civil Litigation",
        "Family Law Offices",
        "Collections Agencies",
        "Customer Support Ops",
      ],
    },
    results: {
      label: "Results that matter",
      headline: "What our clients gain",
      items: [
        { icon: "clock", text: "Shorter hiring cycles with interview-ready candidates." },
        { icon: "dollar", text: "Lower staffing costs than most domestic alternatives." },
        { icon: "users", text: "Stronger retention through close support and alignment." },
        { icon: "zap", text: "Faster ramp-up in U.S. legal workflows." },
      ],
    },
    faq: {
      label: "FAQ",
      headline: "Frequently Asked Questions",
      items: [
        {
          q: "What types of roles can Legal Mate Staffing fill?",
          a: "We place case managers, paralegals, intake specialists, legal assistants, and medical records staff. We also support service teams with customer service, collections, and virtual assistant roles.",
        },
        {
          q: "How do you vet and select candidates?",
          a: "Candidates complete technical screening, role-specific interviews, and background and experience checks. You only see people who pass our standards.",
        },
        {
          q: "Are your professionals bilingual?",
          a: "Yes. Our talent is bilingual in English and Spanish and trained to work with U.S.-based teams across phone, email, and case systems.",
        },
        {
          q: "How quickly can you place a candidate?",
          a: "Most searches deliver qualified candidates within a few business days. Timing depends on role complexity and requirements.",
        },
        {
          q: "What happens if a placement does not work out?",
          a: "We provide ongoing performance support and quick replacements when needed to keep operations stable.",
        },
      ],
    },
    compliance: {
      headline: "Confidentiality and Compliance",
      text: "Our professionals follow strict confidentiality practices, HIPAA-aware workflows, and secure data handling. We are not a covered entity, but we train every placement to meet your compliance expectations.",
    },
    notFound: {
      title: "Page not found",
      message: "The page you\u2019re looking for doesn\u2019t exist or has been moved.",
      backHome: "Back to home",
    },
    footer: {
      tagline: "Remote legal and operations staffing you can trust",
      description: "We help law firms and service teams hire vetted remote professionals who integrate fast.",
      pagesLabel: "Pages",
      servicesLabel: "Services",
      contactLabel: "Contact",
      followUs: "Follow us",
      cta: "Request a Quote",
      legal: "All rights reserved.",
    },
    pages: {
      services: {
        title: "Services",
        subtitle: "Staffing support for legal and service-based teams.",
      },
      about: {
        title: "About Us",
        subtitle: "Built by legal operators who understand law firm workflows.",
        storyLabel: "Who we are",
        storyHeading: "More than recruiters",
        missionLabel: "Our Mission",
        visionLabel: "Our Vision",
        valuesLabel: "Our Values",
        valuesSubhead: "What drives us",
        stats: [
          { value: "5+", label: "Years of legal industry experience" },
          { value: "100%", label: "Remote, bilingual talent" },
          { value: "U.S.", label: "Law firm workflows and systems" },
          { value: "24h", label: "Average candidate turnaround" },
        ],
      },
      process: { title: "Our Process", intro: "How we move from intake to long-term support." },
      requestQuote: {
        title: "Request a Quote",
        subtitle: "Share your hiring needs and we will reply within one business day.",
        formHeading: "Your staffing needs",
        fields: {
          name: "Full name",
          company: "Company / Firm name",
          email: "Work email",
          phone: "Phone number",
          roles: "Roles you are looking to fill",
          positions: "Number of positions",
          timeline: "Ideal start timeline",
          message: "Additional details",
        },
        positionOptions: ["1", "2\u20133", "4\u20136", "7+"],
        timelineOptions: ["Immediately", "Within 2 weeks", "Within 1 month", "Flexible / exploring"],
        submitLabel: "Submit request",
        successHeading: "Thank you!",
        successMessage: "We have received your request and will be in touch within one business day.",
        successCta: "Back to home",
        trustHeading: "Why firms choose us",
        trustPoints: [
          { icon: "clock", text: "Respond within 1 business day" },
          { icon: "shield", text: "Rigorous vetting and background checks" },
          { icon: "globe", text: "Bilingual, U.S.-trained professionals" },
          { icon: "chart", text: "Significant cost savings vs. domestic staffing" },
          { icon: "headset", text: "Ongoing support and performance monitoring" },
        ],
      },
      contact: {
        title: "Contact",
        subtitle: "Talk with our team about your hiring goals.",
        intro: "Talk with our team about your hiring goals.",
        cardTitle: "Contact details",
        reachLabel: "Reach out directly",
        reachSubhead: "We typically respond within one business day.",
        connectLabel: "Connect with us",
        quoteCardHeading: "Ready to get started?",
        quoteCardText: "Send a quick request and we will match you with talent that fits your team.",
        quoteCardCta: "Request a Quote",
      },
    },
    finalCta: {
      headline: "Ready to Get Started?",
      subtext: "Connect with us to discuss your staffing needs. We\u2019re here to help you scale with the right talent.",
      cta: {
        requestQuote: { label: "Request a Quote", href: "/request-quote" },
        bookCall: { label: "Book a Call", href: "#" },
      },
    },
    brand: {
      name: "Legal Mate Staffing",
      logo: "/logo.svg",
      tagline: "Remote legal and operations staffing you can trust",
      colorsNote: "Blue, red, black",
    },
    description:
      "Legal Mate Staffing connects law firms and service businesses with vetted remote professionals, including case managers, paralegals, intake specialists, legal assistants, collections staff, and customer service reps.",
    mission:
      "Connect businesses with reliable talent that improves operations and service quality.",
    vision:
      "Be the staffing partner teams trust for dependable talent, flexible delivery, and consistent quality.",
    values: [
      { icon: "handshake", title: "Partnership", text: "We work as an extension of your team and align talent to real operational needs." },
      { icon: "star", title: "Quality", text: "We prioritize skills, accountability, and measurable performance." },
      { icon: "refresh", title: "Adaptability", text: "We embrace change and evolve with our clients, industries, and workforce demands." },
      { icon: "shield", title: "Professional Integrity", text: "We operate with transparency, responsibility, and respect in every placement and relationship." },
      { icon: "heart", title: "People First Mindset", text: "We value the people behind each role and support fair, professional growth." },
      { icon: "rocket", title: "Growth and Impact", text: "We focus on sustainable client growth and stable career paths for talent." },
    ],
    keyMessage:
      "We are former legal operators, not generic recruiters. That experience helps us screen precisely and place reliable talent that fits your team and workflow.",
    differentiators: [
      {
        icon: "briefcase",
        title: "Real experience in the legal industry",
        text: "Our founders have worked in law firm operations, so we place talent that fits real day-to-day workflows.",
      },
      { icon: "target", title: "Specialization in legal and service industries", text: "We focus on legal and service-sector roles with clear operational standards." },
      { icon: "globe", title: "Bilingual and culturally aligned talent", text: "We provide English-Spanish professionals trained for U.S.-based teams." },
      { icon: "shield", title: "Rigorous selection process", text: "Technical reviews, role interviews, and verification before every shortlist." },
      { icon: "chart", title: "Cost optimization without sacrificing quality", text: "Lower staffing costs while maintaining accountability and output." },
      { icon: "headset", title: "Continuous support and follow up", text: "We stay involved with feedback, monitoring, and replacements when needed." },
      { icon: "layers", title: "Scalability and flexibility", text: "Scale from one hire to full remote teams as needs change." },
      { icon: "handshake", title: "Long term partnerships", text: "We build durable partnerships through transparency and reliable delivery." },
    ],
    services: [
      {
        category: "Remote Legal Staffing",
        items: [
          "Case Managers",
          "Intake Specialists",
          "Paralegals",
          "Legal Assistants",
          "Receptionists",
          "Medical Intake Assistants",
          "Medical Records Clerks",
        ],
        blurb: "Remote legal professionals ready to work inside your existing workflows and case systems.",
      },
      {
        category: "Customer Service and Operations Staffing",
        items: [
          "Customer Service Representatives",
          "Collections Agents",
          "Administrative Support",
          "Virtual Assistant",
        ],
        blurb: "Experienced operations talent to improve service quality and team efficiency.",
      },
    ],
    process: [
      { icon: "phone", step: "Step 1", title: "Initial Contact", text: "You reach out by form, email, WhatsApp, or phone. We reply within one business day." },
      { icon: "search", step: "Step 2", title: "Needs Assessment", text: "We map role requirements, workflows, and outcomes to define the candidate profile." },
      { icon: "filter", step: "Step 3", title: "Candidate Selection", text: "We source and screen candidates, then share a pre-qualified shortlist." },
      { icon: "thumbsUp", step: "Step 4", title: "Interview and Approval", text: "You interview finalists and approve the best fit while we coordinate logistics." },
      { icon: "chart", step: "Step 5", title: "Ongoing Support", text: "We provide follow-up, performance monitoring, and replacement support as needed." },
    ],
    audience: {
      lawFirms: ["Personal Injury Law Firms", "Immigration Law Firms", "Civil Law Firms", "Family Law Firms", "Collections Law Firms"],
      serviceCompanies: ["Collections Agencies", "Customer Support Operations", "Administrative Service Providers", "Companies using Virtual Assistants and Remote Operations Support"],
    },
    founders: [
      {
        initials: "AR",
        name: "Andr\u00e9 Rodriguez Leones",
        title: "Co-Founder, Talent Development",
        bio:
          "Legal operations professional with 5+ years supporting U.S. law firms in case management, medical records, billing, and workflow performance. Leads KPI and reporting initiatives using tools like Power BI, SQL, R, and Excel.",
      },
      {
        initials: "HS",
        name: "Henry Andr\u00e9s S\u00e1nchez Mart\u00ednez",
        title: "Co-Founder, Operations",
        bio:
          "Colombian attorney with 4+ years supporting U.S.-based teams across legal operations, administration, and customer service. Background includes intake, investigation, drafting, demand prep, medical record review, insurance coordination, and collections.",
      },
    ],
    references: [
      { label: "ScaleUp Staffing", url: "https://scaleupstaffing.com/" },
      { label: "Turbo Staffing", url: "https://turbostaffing.com/" },
      { label: "LatHire", url: "https://lathire.com/" },
    ],
    contact: {
      email: "",
      phone: "",
      // WhatsApp: number with country code, digits only (e.g. "1234567890")
      whatsapp: "",
      cityCountry: "",
      hours: "",
      // Calendly (or other booking): full URL (e.g. "https://calendly.com/your-link")
      bookingUrl: "",
      labels: {
        email: "Email",
        phone: "Phone",
        whatsapp: "WhatsApp",
        bookCall: "Book a call",
        bookNow: "Book now",
      },
      social: {
        linkedin: "",
        instagram: "",
        facebook: "",
        tiktok: "",
      },
    },
  };
