export const site = {
    navLinks: [
      { label: "Home", href: "/" },
      { label: "Services", href: "/services" },
      { label: "About", href: "/about" },
      { label: "Process", href: "/process" },
      { label: "Contact", href: "/contact" },
    ],
    hero: {
      badge: "Trusted by law firms nationwide",
      headline: "Remote legal and operations staffing you can trust",
      subheadline: "We connect law firms and service-based businesses with highly skilled professionals\u2014ready to integrate into your team.",
      trustPoints: [
        "Rigorous vetting and legal industry experience",
        "Bilingual talent aligned with U.S. workflows",
        "Scalable from one hire to full remote teams",
      ],
      cta: {
        requestQuote: { label: "Request a Quote", href: "/request-quote" },
        bookCall: { label: "Book a Call", href: "#" },
        whatsapp: { label: "WhatsApp", href: "#" },
      },
    },
    sections: {
      services: "Our Services",
      differentiators: "Why Choose Us",
      differentiatorsSubhead: "Built different. Built to deliver.",
      servicesLabel: "What we do",
      processLabel: "How it works",
      foundersLabel: "The team",
      process: "Our Process",
      founders: "Our Founders",
      finalCta: "Ready to Get Started?",
      finalCtaSubtext: "Connect with us to discuss your staffing needs. We\u2019re here to help you scale with the right talent.",
    },
    trustedBy: {
      label: "Trusted by forward-thinking law firms and service companies",
      logos: [
        "Personal Injury Firms",
        "Immigration Practices",
        "Civil Litigation",
        "Family Law Offices",
        "Collections Agencies",
        "Customer Support Ops",
      ],
    },
    results: {
      label: "Results that matter",
      headline: "What our clients gain",
      items: [
        { icon: "clock", text: "Faster hiring cycles with pre-vetted, interview-ready candidates" },
        { icon: "dollar", text: "Significant cost savings compared to domestic staffing alternatives" },
        { icon: "users", text: "Lower turnover through cultural alignment and ongoing support" },
        { icon: "zap", text: "Immediate productivity from professionals trained in U.S. legal workflows" },
      ],
    },
    faq: {
      label: "FAQ",
      headline: "Frequently Asked Questions",
      items: [
        {
          q: "What types of roles can Legal Mate Staffing fill?",
          a: "We specialize in remote legal roles including case managers, paralegals, intake specialists, legal assistants, and medical records clerks. We also staff customer service representatives, collections agents, and virtual assistants for service-based businesses.",
        },
        {
          q: "How do you vet and select candidates?",
          a: "Every candidate goes through a multi-step process: technical skills evaluation, specialized interviews, background and experience verification, and cultural fit assessment. Only candidates who meet our standards are presented to clients.",
        },
        {
          q: "Are your professionals bilingual?",
          a: "Yes. All of our talent is bilingual in English and Spanish, trained to communicate effectively with U.S.-based teams and clients across phone, email, and case management systems.",
        },
        {
          q: "How quickly can you place a candidate?",
          a: "In most cases, we can present qualified candidates within a few business days of understanding your needs. Timeline depends on role complexity and specific requirements.",
        },
        {
          q: "What happens if a placement does not work out?",
          a: "We provide continuous performance monitoring and fast replacements when needed. Our goal is long-term stability, and we work proactively to resolve any issues before they impact your operations.",
        },
      ],
    },
    compliance: {
      headline: "Confidentiality and Compliance",
      text: "Our professionals are trained to handle sensitive legal and medical information with care. We emphasize confidentiality best practices, HIPAA-aware workflows, and secure data handling protocols in every placement. While we are not a covered entity, we ensure our talent understands and respects the compliance standards your firm operates under.",
    },
    notFound: {
      title: "Page not found",
      message: "The page you\u2019re looking for doesn\u2019t exist or has been moved.",
      backHome: "Back to home",
    },
    footer: {
      tagline: "Remote legal and operations staffing you can trust",
      description: "We connect law firms and service-based businesses with highly skilled remote professionals ready to integrate into your team.",
      pagesLabel: "Pages",
      servicesLabel: "Services",
      contactLabel: "Contact",
      followUs: "Follow us",
      cta: "Request a Quote",
      legal: "All rights reserved.",
    },
    pages: {
      services: {
        title: "Services",
        subtitle: "Specialized staffing solutions for legal and service-based businesses.",
      },
      about: {
        title: "About Us",
        subtitle: "Built by legal professionals, for legal professionals.",
        storyLabel: "Who we are",
        storyHeading: "More than recruiters",
        missionLabel: "Our Mission",
        visionLabel: "Our Vision",
        valuesLabel: "Our Values",
        valuesSubhead: "What drives us",
        stats: [
          { value: "5+", label: "Years of legal industry experience" },
          { value: "100%", label: "Remote, bilingual talent" },
          { value: "U.S.", label: "Law firm workflows and systems" },
          { value: "24h", label: "Average candidate turnaround" },
        ],
      },
      process: { title: "Our Process", intro: "Here is how we work with you from first contact to ongoing support." },
      requestQuote: {
        title: "Request a Quote",
        subtitle: "Tell us about your staffing needs and we will get back to you within one business day.",
        formHeading: "Your staffing needs",
        fields: {
          name: "Full name",
          company: "Company / Firm name",
          email: "Work email",
          phone: "Phone number",
          roles: "Roles you are looking to fill",
          positions: "Number of positions",
          timeline: "Ideal start timeline",
          message: "Additional details",
        },
        positionOptions: ["1", "2\u20133", "4\u20136", "7+"],
        timelineOptions: ["Immediately", "Within 2 weeks", "Within 1 month", "Flexible / exploring"],
        submitLabel: "Submit request",
        successHeading: "Thank you!",
        successMessage: "We have received your request and will be in touch within one business day.",
        successCta: "Back to home",
        trustHeading: "Why firms choose us",
        trustPoints: [
          { icon: "clock", text: "Respond within 1 business day" },
          { icon: "shield", text: "Rigorous vetting and background checks" },
          { icon: "globe", text: "Bilingual, U.S.-trained professionals" },
          { icon: "chart", text: "Significant cost savings vs. domestic staffing" },
          { icon: "headset", text: "Ongoing support and performance monitoring" },
        ],
      },
      contact: {
        title: "Contact",
        subtitle: "Get in touch to discuss your staffing needs.",
        intro: "Get in touch to discuss your staffing needs.",
        cardTitle: "Contact details",
        reachLabel: "Reach out directly",
        reachSubhead: "We typically respond within one business day.",
        connectLabel: "Connect with us",
        quoteCardHeading: "Ready to get started?",
        quoteCardText: "Fill out our quick form and we will match you with the right talent for your team.",
        quoteCardCta: "Request a Quote",
      },
    },
    finalCta: {
      headline: "Ready to Get Started?",
      subtext: "Connect with us to discuss your staffing needs. We\u2019re here to help you scale with the right talent.",
      cta: {
        requestQuote: { label: "Request a Quote", href: "/request-quote" },
        bookCall: { label: "Book a Call", href: "#" },
      },
    },
    brand: {
      name: "Legal Mate Staffing",
      logo: "/logo.png",
      tagline: "Remote legal and operations staffing you can trust",
      colorsNote: "Blue, red, black",
    },
    description:
      "Legal Mate Staffing is your trusted partner for remote legal and operational staffing. We connect law firms and service-based businesses with highly skilled professionals, including case managers, paralegals, intake specialists, legal assistants, collectors, and customer service representatives.",
    mission:
      "To connect businesses with reliable, skilled, and adaptable talent by providing staffing solutions that support operational efficiency, quality service, and long-term growth across multiple industries.",
    vision:
      "To become a trusted staffing partner for companies seeking dependable talent, recognized for our flexibility, quality standards, and people-first approach in an evolving global workforce.",
    values: [
      { icon: "handshake", title: "Partnership", text: "We work as an extension of our clients\u2019 teams, aligning talent with real operational needs and business goals." },
      { icon: "star", title: "Quality", text: "We prioritize skills, accountability, and performance, ensuring our talent delivers consistent and measurable results." },
      { icon: "refresh", title: "Adaptability", text: "We embrace change and evolve with our clients, industries, and workforce demands." },
      { icon: "shield", title: "Professional Integrity", text: "We operate with transparency, responsibility, and respect in every placement and relationship." },
      { icon: "heart", title: "People First Mindset", text: "We value the individuals behind every role, fostering fair opportunities, trust, and professional development." },
      { icon: "rocket", title: "Growth and Impact", text: "We aim to create sustainable growth for our clients while empowering talent to build stable, long-term careers." },
    ],
    keyMessage:
      "At Legal Mate Staffing, we are more than recruiters. We are former legal professionals with over five years of experience working directly with U.S.-based law firms. Because we know the business from the ground up, we apply precise filters and rigorous selection processes to match each client with the most qualified, reliable, and culturally aligned talent.",
    differentiators: [
      {
        icon: "briefcase",
        title: "Real experience in the legal industry",
        text: "Our founding team has directly worked as case managers, intake specialists, legal assistants, paralegals, customer service representatives, and collections agents, so we understand law firm operations and place talent that fits.",
      },
      { icon: "target", title: "Specialization in legal and service industries", text: "We are specialized in legal and service-sector talent with a deep understanding of operational dynamics and standards of excellence." },
      { icon: "globe", title: "Bilingual and culturally aligned talent", text: "We provide bilingual English and Spanish professionals trained to work with U.S.-based teams and clients." },
      { icon: "shield", title: "Rigorous selection process", text: "Technical evaluations, specialized interviews, and experience verification to ensure candidates are prepared from day one." },
      { icon: "chart", title: "Cost optimization without sacrificing quality", text: "Highly qualified remote talent while maintaining performance and accountability." },
      { icon: "headset", title: "Continuous support and follow up", text: "Ongoing monitoring, feedback, and fast replacements when needed to ensure long-term stability." },
      { icon: "layers", title: "Scalability and flexibility", text: "We adapt from hiring one professional to building complete remote teams." },
      { icon: "handshake", title: "Long term partnerships", text: "Strategic partnerships based on trust, transparency, consistent results, and mutual growth." },
    ],
    services: [
      {
        category: "Remote Legal Staffing",
        items: [
          "Case Managers",
          "Intake Specialists",
          "Paralegals",
          "Legal Assistants",
          "Receptionists",
          "Medical Intake Assistants",
          "Medical Records Clerks",
        ],
        blurb: "Highly qualified remote professionals trained to integrate into your workflows and case management systems.",
      },
      {
        category: "Customer Service and Operations Staffing",
        items: [
          "Customer Service Representatives",
          "Collections Agents",
          "Administrative Support",
          "Virtual Assistant",
        ],
        blurb: "Experienced professionals to improve client satisfaction, retention, and operational efficiency.",
      },
    ],
    process: [
      { icon: "phone", step: "Step 1", title: "Initial Contact", text: "Clients reach out via website form, email, WhatsApp, or phone. We respond within one business day to schedule an introductory call." },
      { icon: "search", step: "Step 2", title: "Needs Assessment", text: "We analyze staffing needs, workflows, required skills, and business objectives to build a precise candidate profile." },
      { icon: "filter", step: "Step 3", title: "Candidate Selection", text: "We source, evaluate, and present pre-qualified candidates through technical assessments, interviews, and background checks." },
      { icon: "thumbsUp", step: "Step 4", title: "Interview and Approval", text: "You interview selected candidates and approve the best fit. We coordinate scheduling and handle logistics." },
      { icon: "chart", step: "Step 5", title: "Ongoing Support", text: "Continuous follow-up and performance monitoring through QBRs, using employer-provided metrics to ensure long-term success." },
    ],
    audience: {
      lawFirms: ["Personal Injury Law Firms", "Immigration Law Firms", "Civil Law Firms", "Family Law Firms", "Collections Law Firms"],
      serviceCompanies: ["Collections Agencies", "Customer Support Operations", "Administrative Service Providers", "Companies using Virtual Assistants and Remote Operations Support"],
    },
    founders: [
      {
        initials: "AR",
        name: "Andr\u00e9 Rodriguez Leones",
        title: "Co-Founder, Talent Development",
        bio:
          "Results-driven legal operations professional with over five years of experience supporting U.S.-based law firms in case management, medical records, billing, and operational performance. Leads KPI initiatives and workflow improvements, with experience using Power BI, SQL, R, and Excel to optimize performance and decision-making.",
      },
      {
        initials: "HS",
        name: "Henry Andr\u00e9s S\u00e1nchez Mart\u00ednez",
        title: "Co-Founder, Operations",
        bio:
          "Colombian attorney with over four years of experience working remotely with U.S.-based organizations in legal, administrative, and customer service roles. Experienced across intake, investigation, drafting, demand preparation, medical record analysis, and insurance coordination, with additional experience in collections and high-volume customer service environments.",
      },
    ],
    references: [
      { label: "ScaleUp Staffing", url: "https://scaleupstaffing.com/" },
      { label: "Turbo Staffing", url: "https://turbostaffing.com/" },
      { label: "LatHire", url: "https://lathire.com/" },
    ],
    contact: {
      email: "",
      phone: "",
      // WhatsApp: number with country code, digits only (e.g. "1234567890")
      whatsapp: "",
      cityCountry: "",
      hours: "",
      // Calendly (or other booking): full URL (e.g. "https://calendly.com/your-link")
      bookingUrl: "",
      labels: {
        email: "Email",
        phone: "Phone",
        whatsapp: "WhatsApp",
        bookCall: "Book a call",
        bookNow: "Book now",
      },
      social: {
        linkedin: "",
        instagram: "",
        facebook: "",
        tiktok: "",
      },
    },
  };
